version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - cyclop
    - errcheck
    - errorlint
    - exhaustive
    - gocognit
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - revive
    - staticcheck
    - unused
  settings:
    cyclop:
      max-complexity: 15
    exhaustive:
      default-signifies-exhaustive: true
    gocognit:
      min-complexity: 20
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: exported
        - name: var-naming
        - name: receiver-naming
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - gen
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - gen
      - vendor
      - third_party$
      - builtin$
      - examples$
