syntax = "proto3";

// define a key package within the Boundary controller storage layer
package caas.storage.v1;

option go_package = "github.ibm.com/citius/citius-server/gen/go/store;store";

import "google/protobuf/timestamp.proto";
import "buf/validate/validate.proto";

// Status enumerates the lifecycle statuses of a key
enum StatusV3 {
  STATUSV3_UNSPECIFIED = 0;
  STATUSV3_ACTIVE = 1;
  STATUSV3_SUSPENDED = 2;
  STATUSV3_DESTROYED = 3;
  STATUSV3_PRE_ACTIVE = 4;
  STATUSV3_DEACTIVATED = 5;
  STATUSV3_COMPROMISED = 6;
  STATUSV3_DESTROYED_COMPROMISED = 7;
}

// KeyVersion represents a version of a key with its material
message KeyVersionV3 {
  // @gotags: gorm:"primary_key"
  uint32 id = 1;
  // version number
  // @gotags: gorm:"not_null;uniqueIndex:key_version_idx"
  uint32 version = 2 [(buf.validate.field).string = {prefix: "ver_", min_len: 5}];
  // the public id of the key to which this version belongs
  // @gotags: gorm:"not_null,index;uniqueIndex:key_version_idx"
  string key_id = 3 [(buf.validate.field).string = {prefix: "key_", min_len: 5}];
  // the key to which this version belongs
  // use GORM foreign key
  // @gotags: gorm:"foreignkey:KeyId"
  KeyV3 key = 4;
  // ciphertext key material stored in the database
  // @gotags: gorm:"column:key_material;not_null" wrapping:"ct,key_material"
  bytes ct_key_material = 5;
  // plain text version of the decrypted key material
  // we are NOT storing this plain-text key material in the db
  // @gotags: gorm:"-" wrapping:"pt,key_material"
  bytes key_material = 6;
  // Template associated with the key material
  // @gotags: gorm:"not_null"
  string template_id = 7;
  // digest used for integrity checks
  // @gotags: gorm:"not_null"
  bytes digest = 8;
  // digest algorithm used to calculate the digest
  // @gotags: gorm:"not_null"
  string digest_algorithm = 9;
  // id of the key used to encrypt the key material
  // @gotags: gorm:"not_null"
  string wrapping_key_id = 10 [(buf.validate.field) = {ignore: IGNORE_IF_ZERO_VALUE, string: {prefix: "key_", min_len: 5}}];
  // id of the provider where the key lives
  // @gotags: gorm:"not_null"
  string provider_id = 11 [(buf.validate.field).string = {prefix: "prv_", min_len: 5}];
  // Lifecycle state of the key version
  // @gotags: gorm:"not_null"
  StatusV3 status = 12;
}

// Key represents a cryptographic key stored in the database
message KeyV3 {
  // @gotags: gorm:"primary_key"
  string public_id = 1 [(buf.validate.field).string = {prefix: "key_", min_len: 5}]; 
  // @gotags: gorm:"not_null"
  string key_name = 2 [(buf.validate.field).string = {min_len: 1, max_len: 256}];
  // @gotags: gorm:"not_null"
  string primitive = 3;
  // @gotags: gorm:"not_null"
  bytes scope_specification = 4;
  // @gotags: gorm:"not_null"
  string policy_id = 5 [(buf.validate.field).string = {prefix: "pol_", min_len: 5}];
  // key's versions
  // @gotags: gorm:"foreignkey:key_id"
  repeated KeyVersionV3 versions = 6;
  // id of the current version of the key
  // @gotags: gorm:"not_null"
  uint32 current_version_id = 7 [(buf.validate.field).uint32.gte = 1];
//   // Labels associated with the key
//   map<string, string> labels = 8;
}
