package software

import (
	"context"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"

	types "github.com/agile-crypto/citius-api-go/gen/go/types"
	"github.com/agile-crypto/citius-core/errors"
)

// checkAESCTRParamsValid rejects a nonce_size_bits/counter_bits split this
// provider does not implement.
//
// AesCtrParams' CEL rules constrain each field independently (nonce_size_bits
// in {64,96}, counter_bits in [1,128]) but declare no cross-field rule tying
// them together — nothing stops a request from combining, say, a 64-bit
// nonce with a 32-bit counter (leaving 32 bits of the counter block
// unaccounted for). Every AES-CTR catalog entry uses the 96-bit-nonce +
// 32-bit-counter split (NIST SP 800-38A, Appendix B.2); that is the only
// split this provider builds the counter block for, so anything else is
// rejected defensively rather than guessed at.
func checkAESCTRParamsValid(ctx context.Context, op errors.Op, nonceSizeBits, counterBits uint32) error {
	const (
		wantNonceSizeBits = 96
		wantCounterBits   = 32
	)
	if nonceSizeBits != wantNonceSizeBits || counterBits != wantCounterBits {
		return errors.New(ctx, op, errors.CodeNotImplemented,
			"unsupported AES-CTR nonce/counter split: %d/%d bits (only 96/32 is implemented)", nonceSizeBits, counterBits)
	}
	return nil
}

// newAESCTRBlock validates the request and constructs the underlying AES
// block cipher shared by encryptAESCTR and decryptAESCTR.
func newAESCTRBlock(ctx context.Context, op errors.Op, keyMaterial []byte, params *types.AesCtrParams) (cipher.Block, error) {
	if err := checkAESKeyMatchesDeclaredSize(ctx, op, keyMaterial, params.GetKeySizeBits()); err != nil {
		return nil, err
	}
	if err := checkAESCTRParamsValid(ctx, op, params.GetNonceSizeBits(), params.GetCounterBits()); err != nil {
		return nil, err
	}
	block, err := aes.NewCipher(keyMaterial)
	if err != nil {
		return nil, errors.Wrap(ctx, op, err)
	}
	return block, nil
}

// encryptAESCTR encrypts plaintext under a freshly generated random nonce.
// CTR is a stream cipher: the "ciphertext" is plaintext XORed with a
// keystream generated by encrypting successive values of a 128-bit counter
// block (nonce || counter, counter starting at zero) — there is no padding
// and no built-in integrity check, unlike AES-GCM.
func encryptAESCTR(ctx context.Context, keyMaterial, plaintext []byte, params *types.AesCtrParams) (ciphertext, iv []byte, _ error) {
	const op errors.Op = "software.encryptAESCTR"

	block, err := newAESCTRBlock(ctx, op, keyMaterial, params)
	if err != nil {
		return nil, nil, err
	}

	// iv is the initial counter block: nonce || zero-initialized counter.
	// Only the nonce portion is randomized — the counter starts at zero and
	// cipher.NewCTR increments the whole 16-byte block as it consumes
	// keystream, which is exactly the 96-bit-nonce/32-bit-counter split
	// checkAESCTRParamsValid enforces.
	iv = make([]byte, aes.BlockSize)
	nonceSizeBytes := params.GetNonceSizeBits() / 8
	if _, err = rand.Read(iv[:nonceSizeBytes]); err != nil {
		return nil, nil, errors.Wrap(ctx, op, err)
	}

	ciphertext = make([]byte, len(plaintext))
	cipher.NewCTR(block, iv).XORKeyStream(ciphertext, plaintext)
	return ciphertext, iv, nil
}

// decryptAESCTR decrypts ciphertext using the counter block recorded at
// encryption time. CTR decrypt is the identical XOR-with-keystream
// operation as encrypt — there is no separate "unpad" or "verify" step, so
// unlike AES-CBC/AES-GCM's decrypt, a wrong key or IV here does not surface
// as an error; it silently produces garbage plaintext. That is inherent to
// unauthenticated CTR mode, not a gap in this implementation — the proto's
// own doc comment on AesCtrParams notes "requires separate MAC for
// authentication (not AEAD)".
func decryptAESCTR(ctx context.Context, keyMaterial, ciphertext, iv []byte, params *types.AesCtrParams) ([]byte, error) {
	const op errors.Op = "software.decryptAESCTR"

	block, err := newAESCTRBlock(ctx, op, keyMaterial, params)
	if err != nil {
		return nil, err
	}
	if len(iv) != aes.BlockSize {
		return nil, errors.New(ctx, op, errors.CodeInvalidArgument, "IV is %d bytes, want %d bytes", len(iv), aes.BlockSize)
	}

	plaintext := make([]byte, len(ciphertext))
	cipher.NewCTR(block, iv).XORKeyStream(plaintext, ciphertext)
	return plaintext, nil
}
