name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    name: ci          
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install buf
        uses: bufbuild/buf-setup-action@v1

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: binary
          skip-cache: false

      - name: Run CI gate
        run: make ci
